### PR TITLE
Lab2 submission

### PR DESCRIPTION
**Pull request by victoriafil**
I am getting a "POST https://api.openai.com/v1/chat/completions 401" error and an uncaught type error error on line 901. I am not sure as to why.

### CODE REVIEW

**Comment by vladmaraev** [comment]
I run it, gave it an arbitrary input and it seems that it successfully gets some information from ChatGPT. It just says "[Object object]" but I guess it is fixable. Can you provide a full error output that it gives for line 901 (I assume your type-checker gives this error). It seems like again a difference between Windows and Linux/macOS. Perhaps, `tsc` doesn't see the `tsconfig.json` file.

**Comment by victoriafil** [comment]
ok I feel a little silly, I was getting the POST error because I hadn't removed the <>. Thanks! 
The type error is different now: 
"index.ts:904 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at index.ts:904:41
    at async index.ts:353:38"

**Comment by victoriafil** [comment]
Actually after fixing this and accessing the correct thing for GPT's answer now I don't have this type error!

**Comment by victoriafil** [comment]
The report for this lab: 

For this lab’s purposes I experimented with the ChatGPT API in the following ways:
1.	**Adjusting the temperature:** The temperature setting when 0.8 – 1.0 can give more diverse or creative responses in contrast to low temperatures like 0.2 – 0.5. However, when experimenting with this I always got the same book suggestions by ChatGPT, no matter the value I chose. Sometimes, it was the same book for as many times as I started the speechstate from the beginning. My speculation as to why this happened, is that the JSON format I’m requesting is quite restrictive and there is not a lot of freedom for GPT to be creative.
2.	**Prompt engineering:** To get different answers from ChatGPT, I used different prompts in combination with the user’s utterance. For example, “don’t answer if the utterance is a question”, to avoid getting any comments by GPT like “certainly” or “sure”, because that would make the system crash. Moreover, I asked it to be more diverse, because I was being recommended “The Great Gatsby” every time I didn’t know what to read, but that just ended up GPT recommending less expected books in the same repetitive manner.
3.	**Generating book suggestions/dialogues:** I thought that it made more sense to use GPT only at the start of my state chart, and I also tried to invoke it later in it, to allow the user to freely discuss with it about the book and save their dialogue/discussion. I thought this would be a nice way to see how different users interact with it and it might also be helpful for dialogue designing later. Even if it’s not considered to be the most natural interaction that can exist, it can help in pointing out things that sound off and make them sound more human like when delving in the designing process and note down how the user asks for things. The only backdraw in this that I can think, is that it cannot be stopped after entering this state. Also, I  couldn’t make the code work the way I wanted because in the end ChatGPT got in an endless discussion with itself.

**Comment by vladmaraev** [comment]
Well done!

**Pull request closed without merging**
